source "https://rubygems.org"
gem "ruboty"
gem "ruboty-slack"
gem "ruboty-talk"
#gem "ruboty-hitozuma"
gem "ruboty-magi"
gem "ruboty-zoi"
gem "ruboty-ruby"
gem "ruboty-tiqav", github: 'cignoir/ruboty-tiqav'
#gem "ruboty-lgtm"
